### ISSUE TITLE
[FEATURE] add support for "record search" states in the IDE

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1009]
The new state should allow the user to identify a data provider.  The data provider must have the `supports_read` property set to `true`.

The state should also allow the user to specify the search criteria and search options.

Search criteria: a hash where keys are field names (as returned by the record type of the data provider; ex: `GET /api/latest/connections/omquser/provider/bb_local/record`) and values are a hash in the following format:
- `op`: an operator 
- `arg`: the operator argument

Supported operators to be retrieved from a server API call (TBD).  For now `op` can always be `=` for equality (each data provider may support a different set of search operators for native search functionality; there is also a core set of operators common to all data providers).

Search options are returned by the `search_options` attribute of the data provider (ex: `GET /api/latest/connections/omquser/provider/bb-local/search_options`)

state attributes:
- `type` (string - required): for identifying the provider
- `name` (string - required): for identifying the provider
- `path` (*string - optional): for identifying the provider
- `options` (*hash - optional): for data provider factory constructor options
- `search_args` (hash - required): the search criteria
- `search_options` (*hash - optional): the search options
- `requires_result` (bool - required, default `false`): no row is matched, then the server will throw an exception

YAML state type: `search-single` - example data:
```
        action:
            type: search-single
            value:
                type: datasource
                name: omquser
                supports_read: true
                path: /bb_local
                search_options:
                    columns:
                        type: list
                        value: 
                            - col_1
                search_args:
                    remote_id:
                        type: string
                        value: '1'
                        op: '!='
```

EDIT: proposed generic search criteria - made up of nested expressions of 3 types:
- `clause` - a set of boolean expressions with value `and` or `or` - always returns type `bool` - takes any nuymber of arguments of type `bool`
- `operator` - an operator expression - each operator is like a function returning a value of a certain type and taking arguments of a certain type - for example `clause` arguments can only take operators returning `bool`
- `field-reference` - a reference to a known field, the value used is the field's value and the return type is the field's type
- `value` - any literal value
ex:
```
exp:
  type: clause
  value: and
  args:
    - type: operator
      value: '!='
      args:
         - type: field-reference
           value: remote_id
         - type: value
           value: 1
    - type: clause
      value: or
      args:
        - type: operator
          value: '>='
          args:
            - type: field-reference
              value: local_id
            - type: value
              value: 10
        - type: operator
          value: '='
          args:
            - type: field-reference
              value: order_type
            - type: value
              value: 'EXPEDITED'
```
