### ISSUE TITLE
[BUG] WebView crashes opening API call state

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1086]
opening the `Get XML Data` state in the attached fsm
`call-web-service.qfsm.yaml`:
```
# This is a generated file, don't edit!
type: fsm
name: call-web-service
desc: maps the input data and then makes a REST API call
groups:
  - EXAMPLES
states:
    '1':
        position:
            x: 89
            'y': 59.372528076171875
        initial: true
        name: Get XML Data
        desc: ''
        type: state
        id: k-xFm3P0S
        action:
            type: apicall
            value:
                type: factory
                name: qorus-api
                is_api_call: true
                supports_request: true
                supports_read: false
                supports_update: false
                supports_create: false
                supports_delete: false
                descriptions:
                    - >-
                        Top-level Qorus API data provider; request/response (API) data
                        providers are provided as children
                    - >-
                        Top-level Qorus API data provider; request/response (API) data
                        providers are provided as children
                    - >-
                        Data provider providing child request-response data providers
                        representing supported Data Provider APIs in Qorus
                    - >-
                        Top-level Qorus API data provider; request/response (API) data
                        providers are provided as children
                    - >-
                        Data provider providing child request-response data providers
                        representing supported Data Provider APIs in Qorus
                    - >-
                        Request/response data provider: performs a search in the given
                        data provider and returns the results as output data.
        
        
                        This API also includes arguments that allow it to do inline
                        recoveries from technical errors; by default up to 3 retries are
                        made up to 5 seconds apart; see the `retries`, `retry-delay`,
                        and `retry-errors` arguments.
                path: /data-provider/search
                use_args: true
                args:
                    type: hash
                    value:
                        provider-path:
                            type: data-provider
                            value: >-
                                factory/sax{element_name=DetailRecord,location=datra://$static:xml}
                        requires-result:
                            type: bool
                            value: false
                        retries:
                            type: int
                            value: 3
                        retry-delay:
                            type: int
                            value: 5
        execution_order: 1
        transitions:
            -
                state: '2'
                language: qore
    '2':
        position:
            x: 358
            'y': 57.372528076171875
        initial: false
        name: POST REST Message
        desc: ''
        type: state
        id: WDOIZEzcH
        action:
            type: apicall
            value:
                type: connection
                name: rest-example
                is_api_call: true
                supports_request: true
                supports_read: false
                supports_update: false
                supports_create: false
                supports_delete: false
                descriptions:
                    - Data provider for REST servers
                    - >-
                        REST POST data provider; makes a `POST` request to a REST server
                        and returns the response
                path: /post
                use_args: true
                args:
                    type: hash
                    value:
                        path:
                            type: string
                            value: data
                        body:
                            type: data
                            value: |-
                                filename: $static:filename
                                data: $local:input
        transitions:
            -
                state: '3'
                language: qore
    '3':
        position:
            x: 610
            'y': 58.372528076171875
        initial: false
        name: Log Response
        desc: ''
        type: state
        id: 1hZs2KJ0b
        action:
            type: apicall
            value:
                type: factory
                name: qorus-api
                is_api_call: true
                supports_request: true
                supports_read: false
                supports_update: false
                supports_create: false
                supports_delete: false
                descriptions:
                    - >-
                        Top-level Qorus API data provider; request/response (API) data
                        providers are provided as children
                    - >-
                        Top-level Qorus API data provider; request/response (API) data
                        providers are provided as children
                    - >-
                        Data provider providing child request-response data providers
                        representing supported utility APIs in Qorus
                    - >-
                        Top-level Qorus API data provider; request/response (API) data
                        providers are provided as children
                    - >-
                        Data provider providing child request-response data providers
                        representing supported utility APIs in Qorus
                    - >-
                        Request/response data provider: writes a log message to the
                        current log file.
        
        
                        This API call can only be made internally in Qorus.
        
        
                        This API call does not return any response.
                path: /util/log-message
                use_args: true
                args:
                    type: hash
                    value:
                        level:
                            type: select-string
                            value: INFO
                        message:
                            type: string
                            value: 'response: %Y'
                        args:
                            type: auto
                            value: '$local:input'
```
