### ISSUE TITLE
[FEATURE] Add support for mappers

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#110]
Add support for mappers. Add possibility to add code (using functions from function objects - for that we need to implement function creation page first). Code for an output field can also be used with one input field. User should not be able to connect more than 1 input field with one output field (this can be achived using a code block), but should be able to connect one input with more outputs. Also add support for defining constant values for ouput fields (only basic type validation support for the start):

```
fields:
  output_1:
    constant: 123
```

Child inputs/outputs should be stored in yaml like this:
```
fields:
  output_1:
    name: input.input_1
  output_2.test:
    name: input_1
```

Support sequences in mappers for output fields and only in case user has datasource as an output provider. The valid output keys like sequence etc should bein the rest API.

Example of generated mapper (input and output are dataprovider types):
```
name: crm-to-erp-order
type: mapper
version: "1.0"
desc: maps salesforce account update events to workflow order data
mappertype: Mapper
author:
  - Qore Technologies, s.r.o.
parse-options:
  - PO_NEW_STYLE
groups:
  - iot-demo
functions:
  - crm-to-erp-account-sync-functions

options:
  input-type: qorus:bb_salesforce:stream-event
  output-type: qorus:create-order

fields:
  staticdata:
    name: payload
  workflow_unique_key:
    name: event.replayId
    code: get_event_id
  orderkeys:
    name: payload.ChangeEventHeader.recordIds
    code: get_account_ids
```

Supported options:
```
output (TBD)
output-type (see example above)
output-factory
output-connection
output-datasource

input (TBD)
input-type (see example above)
input-factory
input-connection
input-datasource
```
