### ISSUE TITLE
[FEATURE] implement support for free-form record creation in the FSM create state

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1138]
The current FSM state allows users to build new records manually by selecting the fields and providing values.

A more useful approach would be to make the record set input freeform, which should be the new default for the state.

To do this, the IDE can allow the user to enter in YAML which should be either a hash or a list of hashes.  The server will then resolve the value with template resolution and then use the resulting data to create records in the data provider.

The user should be allowed to choose the "guided" approach (the current default where each column must be selected and values must be entered manually) or the "freeform" approach.

The new data in the FSM yaml will look like:
```
                create_args_freeform:
                    - col_1: 4
                      col_2: number 4
                    - col_1: 5
                      col_2: number 5
```

Qorus will support both formats.  The IDE must be able to automatially recorgnize and support FSM state data in both formats (i.e. with `create_args` -> guided or `create_args_freeform` -> freeform)
