### ISSUE TITLE
[FEATURE] implement support for FSM send message states

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1169]
"Send message" states (icon: TbMessageCircle) are somewhat similar to API call states - the differences are:
- there is a new `message_id` string attribute - this must be one of the message IDs supported by the data provider
- the "allow API arguments" is implied to be `true` - the user always needs to povide the message body, if a message body is required

To look for a suitable data provider, the following attributes should be used - with client-side filtering:
- `supports_messages` != `NONE` (valid values are `ASYNC` and `SYNC`)
- `children_can_support_messages` = `True`

With the new browsing API:
- `context` = `message`

The user must be prompted for the `message_id` value, which should be a supported message as seen here:
```
...
  messages : hash: (4 members)
    data : hash: (3 members)
      desc : "An outgoing WebSocket message that will be serialized according to the serialization option"
      type : "auto"
      type_info : hash: (11 members)
        name : "auto"
        desc : "Qore data type \"auto\""
        supported_options : <NOTHING>
        options : <NOTHING>
        base_type : "auto"
        mandatory : False
        types_accepted : list: (1 element)
          [0]="any"
        types_returned : list: (1 element)
          [0]="any"
        fields : <EMPTY HASH>
        can_manage_fields : True
        tags : <NOTHING>
    ping : hash: (3 members)
      desc : "A WebSocket `PING` message; should result in a `PONG` event being raised by the remote end"
      type : "*data"
      type_info : hash: (11 members)
        name : "*data"
        desc : "Qore data type \"*data\""
        supported_options : <NOTHING>
        options : <NOTHING>
        base_type : "data"
        mandatory : False
        types_accepted : list: (4 elements)
          [0]="string"
          [1]="binary"
          [2]="nothing"
          [3]="null"
        types_returned : list: (3 elements)
          [0]="string"
          [1]="binary"
          [2]="nothing"
        fields : <EMPTY HASH>
        can_manage_fields : False
        tags : <NOTHING>
...
```

ex:
```
> PUT /api/latest/dataprovider/browse/factory/wsclient/info HTTP/1.1
> {provider_options: {url: "wss://sandbox:sandbox@localhost:8011/creator"}}
```

Example YAML:
```
        action:
            type: send-message
            value:
                type: factory
                name: wsclient
                options:
                    url:
                        type: string
                        value: $sysprop:{issue-3974.url}
                    data:
                        type: string
                        value: none
                is_api_call: false
                supports_request: false
                supports_read: false
                supports_update: false
                supports_create: false
                supports_delete: false
                supports_messages: ASYNC
                descriptions:
                    - >-
                        WebSocket client to URL "wss://localhost:8011/creator"
                    - >-
                        WebSocket client to URL "wss://localhost:8011/creator"
                path: /
                message_id: data
                message:
                    type: string
                    value: test
```
