### ISSUE TITLE
[FEATURE] implement support for FSM variable declarations and variable operation states

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1172]
Variables should be declarable in any FSM / block.  At the top-level of an FSM, the "global" variables should be declarable - these will be `$transient:...` variables.  These variables should be global to the entire FSM.  "local" variables are `$var:...` variables and are local to each block - i.e. if a block declares a "local" / `$var:...` variable, then a subblock can redefine the same variable name with a new definition.

The user should be able to see the variable declarations somewhere in the FSM - should be able to create / update / delete them.

Variables should be declared with a specified type - this can be any supported data type, or the special `data-provider` type, in which case the IDE should prompt the user to choose a specific data provider - this is important, as each variable then should support operations on the variable as well in new FSM states, and supported operations will depend on the capabilities of the data provider chosen.

The user should be able to create new FSM states from data provider variables - these states will execute operations on the variable.

If the data provider supports transactions (i.e. has `transaction_management = true`), then 3 simple operation states should be supported - none of which support any options - the transaction state operation name is enough:
- `begin-transaction`: starts a transaction on the data provider
- `commit`: commits the active transaction on the data provider
- `rollback`: rolls the active transaction back on the data provider

ex YAML (TBD):
```
transient:
    datasource:
        type: data-provider
        value:
                type: datasource
                name: omquser
                supports_read: true
                supports_update: true
                supports_create: true
                supports_delete: true
                supports_messages: NONE
                transaction_management: true
                descriptions:
                    - >-
                        Data provider for database `pgsql:omquser@omquser`; use the
                        search API with the `sql` and `args` arguments to execute
                        record-based queries
                    - >-
                        Record-based data provider for db table `public.test_table_1`;
                        supports create, read/search, update, delete, upsert, and bulk
                        operations
                path: /test_table_1
states:
    '1':
        position:
            x: 58.546875
            'y': 44.546875
        initial: true
        name: Commits the transaction
        desc: commits the transaction
        type: state
        id: lZQ0oTyNB
        action:
            type: var-action
            value:
                var_type: transient
                var_name: datasource
                action_type: transaction
                transaction_action: commit 
```

The above example declares a "global" `$transient` variable "datasource" and then has one `var-action` state for the action to commit the transaction.

If the data provider supports records, then any of the record-based states should be creatable from the variable, except the data for the data provider should reference the variable instead of the data provider itself - as in the following example for a `search-single` state based on a `var` variable declaration:
```
var:
    datasource:
        type: data-provider
        value:
                type: datasource
                name: omquser
                supports_read: true
                supports_update: true
                supports_create: true
                supports_delete: true
                supports_messages: NONE
                transaction_management: true
                descriptions:
                    - >-
                        Data provider for database `pgsql:omquser@omquser`; use the
                        search API with the `sql` and `args` arguments to execute
                        record-based queries
                    - >-
                        Record-based data provider for db table `public.test_table_1`;
                        supports create, read/search, update, delete, upsert, and bulk
                        operations
                path: /test_table_1
states:
    '1':
        position:
            x: 58.546875
            'y': 44.546875
        initial: true
        name: Searches for a record
        desc: searches for a record
        type: state
        id: lZQ0oTyNB
        action:
            type: var-action
            value:
                var_type: var
                var_name: datasource
                action_type: search-single
                search_options:
                    requires_result:
                        type: bool
                        value: false
                search_args:
                    col_1:
                        type: number
                        value: 1
                        op:
                            - '='
```

The above example declares a "local" `$var` variable "datasource" and then has one `var-action` state for the action to perform the search on the state.

If the data provider supports API calls or messages, then API or send message states should be creatable from the variable in a similar way.

One way for handling that could be that the user will see the variables in the palette and then an accordion for available actions on the variable that has entries that can be dragged on to the canvas for execution in the FSM.
