### ISSUE TITLE
[FEATURE] implement support for "automatic variables" in FSMs for event handling from services

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1173]
requires #1175 to be implemented first

In the context of an event from a service connected to an FSM for execution, FSMs should support an "automatic variable context" - this would add another variable type of `auto` in addition to `transient` and `var` in the context of #1172  

This context should be created automatically by the IDE in case the FSM is created for the service to handle a specific event - the context should give the description of the event-based data provider as in the following example (YAML TBD):
```
        type: factory
        name: wsclient
        options:
            url:
                type: string
                value: $sysprop:{ws-url}
            data:
                type: string
                value: none
        is_api_call: false
        supports_request: false
        supports_read: false
        supports_update: false
        supports_create: false
        supports_delete: false
        supports_messages: ASYNC
        descriptions:
            - >-
                WebSocket client to URL "wss://localhost:8011/apievents"
            - >-
                WebSocket client to URL "wss://localhost:8011/apievents"
        path: /
```

This event context should be shown in the main FSM config page as well.

The IDE then needs to make a REST call (available with Qorus 6.0.1+) to retrieve the auto var info based on the context - the call is: 
- `PUT /api/latest/system/autoVarContext`
- the message body will have a hash with 2 arguments - `type: event` (from `type` above) and `provider` (from `provider` above)

ex request:
```
> PUT /api/latest/system/autoVarContext HTTP/1.1
> {type: "event", provider: {type: "factory", name: "wsclient", options: {url: "wss://localhost:8092/apievents"}}}
```

ex response:
```
hash: (2 members)
  event_id : hash: (2 members)
    type : "string"
    desc : "the event ID of the event received"
  event_provider : hash: (3 members)
    type : "data-provider"
    desc : "the data provider that produced the event"
    value : hash: (37 members)
     // Add the event info here (name, path, type, options ...)
      supports_read : False
      supports_create : False
      supports_update : False
      supports_upsert : False
      supports_delete : False
      supports_native_search : False
      supports_bulk_read : False
      supports_bulk_create : False
      supports_bulk_upsert : False
      supports_request : False
      supports_children : False
      transaction_management : False
      has_record : False
      record_requires_search_options : False
      supports_child_create : False
      supports_child_delete : False
      supports_add_field : False
      supports_update_field : False
      supports_delete_field : False
      supports_schema : False
      supports_search_expressions : False
      supports_observable : True
      supports_messages : "ASYNC"
      children_can_support_apis : False
      children_can_support_records : False
      children_can_support_observers : False
      children_can_support_messages : False
      children_can_support_transactions : False
      search_logic_capabilities : 3
      mapper_keys : hash: (15 members)
        context : hash: (4 members)
          desc : "the option's value will be processed by UserApi::expandTemplatedValue(), and the resulting value will be used"
          value_type : "string"
          requires_field_type : False
          unique_roles : list: (1 element)
            [0]="value"
...
```

The auto vars should then be shown the same as the other variables, but auto vars are read-only - meaning they cannot be edited or deleted - they can just be used for operations.

`var_type` for an auto var will be `auto` - ex:
```
        action:
            type: var-action
            value:
                var_type: auto
                var_name: event_provider
                action_type: ...
```
