### ISSUE TITLE
[FEATURE] implement support for event-based data provider sources in services

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1175]
Allow the user to add one or more `events` to a service - which will be a data provider that supports events.

To pick such a data, the client-side API in the IDE will search for:
- `supports_observable = true` (to allow the data provider to be chosen)
- `children_can_support_observers = True` (to support filtering in parent data providers or factories)

Using the server-side data provider browse API, use `context = event`

The event source then will be associated with a method or an FSM as a handler.  The user does not need to select the event type - all events will be sent to the message / FSM.

Example service YAML (TBD):
```
events:
  - type: factory
    name: filepoller
    options:
        path:
            type: string
            value: $config:{path}
        mask:
            type: string
            value: "*.txt"
        poll_interval:
            type: int
            value: 1
    handlers:
        file-event:
            type: method
            value: event
 - type: factory
    name: filepoller
    options:
        path:
            type: string
            value: $config:{path}
        mask:
            type: string
            value: "*.txt"
        poll_interval:
            type: int
            value: 1
    handlers:
        file-event:
            type: method
            value: event
```

example test service in the qorus sources: `test/issue-3881/issue-3881-1.0.qsd.yaml`

see #1173
