### ISSUE TITLE
[BUG] IDE serializes YAML values in value maps incorrectly

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1226]
ex:
```
value-maps:
    10-Retail:
        value: HO : RR : RRT : RETL
        enabled: true
```

error: `YAML-PARSER-ERROR: getEvent: unexpected event 'empty' when parsing YAML document`

The value string above, `HO : RR : RRT : RETL`, must be quoted to be valid:
```
value-maps:
    10-Retail:
        value: "HO : RR : RRT : RETL"
        enabled: true
```
