### ISSUE TITLE
[BUG] config item option values for "data-provider" items are saved with incorrect data

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1233]
ex:
```
        config-items:
          - name: record-create-processor-data-provider
            value:
                {"type":"factory","name":"csvwrite","path":"","descriptions":[null,null,null,null],"options":{"path":{"type":"string","value":"/Users/david/src/Qorus/git/julius-meinl/data/netsuite-accounting-import-$qore-expr:{now_us().format(\"IF\")}.cs"}}}
            parent:
                interface-type: class
                interface-name: BBM_DataProviderRecordCreateProcessor
                interface-version: '1.0'
```

note the invalid `descriptions` value above
