### ISSUE TITLE
[BUG] config items of type data provider cannot be read after saving

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#1234]
steps to reproduce:
- create a pipeline with a `BBM_DataProviderRecordCreateProcessor` processor and set a data provider
- save the pipeline
- reload the window or restart VS Code
- connect to Qorus
- open the pipeline and look at the config item and check the value

in this case the IDE cannot display the config item value.  If you check the config item value after saving, it opens correctly, just after resetting the IDE, the config item value cannot be displayed properly for some reason

**Comment by davidnich** [comment]
reopened - config items of type `data-provider` are saved properly but cannot be read:
<img width="1701" alt="Screenshot 2023-10-26 at 9 56 16 AM" src="https://github.com/qoretechnologies/qorus-vscode/assets/13432105/4d614649-287e-46a0-8425-856cfd7ec190">

YAML:
```
        config-items:
          - name: record-create-processor-data-provider
            value:
                "factory/csvwrite{path=/Users/david/src/Qorus/git/julius-meinl/data/netsuite-accounting-import-$timestamp:{IF}.csv,date_format=IF}"
            parent:
                interface-type: class
                interface-name: BBM_DataProviderRecordCreateProcessor
                interface-version: '1.0'
```
