### ISSUE TITLE
[FEATURE] Add support for connecting building blocks

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#164]
Add support for connecting building blocks. Details TBD.

**Comment by turlyalz** [comment]
Example of how it can be stored on the FS:

Metadata:
```
# BBM_SalesforceStreamBase.yaml
class-connectors:
 - name: BBM_SalesforceStreamBase_connector_1
   method: messageCallbackImpl
   output-type: qore:sftp:event
 - name: BBM_SalesforceStreamBase_connector_2
   method: messageMessage2
   input-type: qore:sftp:event

# BBM_CreateOrder.yaml:
class-connectors:
 - name: BBM_CreateOrder_connector
   method: createWorkflowOrder
   input-type: qorus:create-order

# TestInterface.yaml:
class-connections:
  - from:
      class: BBM_SalesforceStreamBase
      connector: BBM_SalesforceStreamBase_connector_1
    to: 
      class: BBM_CreateOrder
      prefix: prefix_1
      connector: BBM_CreateOrder_connector
    mapper: mapper_bb1_to_bb2

  - from:
      class: BBM_SalesforceStreamBase
      connector: BBM_SalesforceStreamBase_connector_1
    to: 
      class: BBM_CreateOrder
      connector: BBM_CreateOrder_connector
      prefix: prefix_2
    mapper: mapper_bb1_to_bb2
```

Code:
```

class TestInterface inherits BaseClass {
    private {
        #### GENERATED SECTION! DON'T EDIT! ####
        # map of class with prefixes to class instances
        hash<auto> class_with_prefixes = {
            "BBM_SalesforceStreamBase": new BBM_SalesforceStreamBase(),
            "prefix1_BBM_CreateOrder": new BBM_CreateOrder("prefix_1"),
            "prefix2_BBM_CreateOrder": new BBM_CreateOrder("prefix_2"),
        };
        #########################################
    }

    #### GENERATED SECTION! DON'T EDIT! ####
    auto callClassWithPrefixMethod(string class_with_prefix, string method) {
        return call_object_method_args(class_with_prefixes{class_with_prefix}, method, argv);
    }

    # CONNECTOR MAPPING #
    private messageCallbackImpl(hash<auto> mh) {
        auto mapper;
        auto mapped_data;
        
        # BBM_SalesforceStreamBase_connector_1 -> BBM_CreateOrder_connector (prefix1)
        
        mapper = getMapper("mapper_bb1_to_bb2");
        mapper_data = mapper.mapData(mh);
        callClassWithPrefixMethod("prefix1_BBM_CreateOrder", "createWorkflowOrder", mapped_data_1);

        # BBM_SalesforceStreamBase_connector_2 -> BBM_CreateOrder_connector (prefix2)
        mapper = getMapper("mapper_bb1_to_bb2");
        mapped_data = mapper.mapData(mh);
        callClassWithPrefixMethod("prefix2_BBM_CreateOrder", "createWorkflowOrder", mapped_data_1);
    }

    #########################################

    #### GENERATED SECTION! DON'T EDIT! ####
    # Only for services
    start() {
        map $1.start(), class_with_prefixes.iterator(), $1.hasCallableMethod("start");
    }

    stop() {
        map $1.stop(), class_with_prefixes.iterator(), $1.hasCallableMethod("stop");
    }

    # Only for jobs
    run() {
        map $1.run(), class_with_prefixes.iterator(), $1.hasCallableMethod("run");
    }

    # Only for steps
    primary() {
        map $1.primary(), class_with_prefixes.iterator(), $1.hasCallableMethod("primary");
    }

    #########################################
}
```
