### ISSUE TITLE
[BUG] Manage config items button shows the wrong number of config items

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#218]
ex as in the screenshots: it shows 9 when there are only 3
![Screen Shot 2019-12-29 at 7 05 01 PM](https://user-images.githubusercontent.com/13432105/71560747-2abcb200-2a6e-11ea-9de7-d54e1164d9cb.png)

yaml:
```
type: step
name: Mip70ItFinalizeR11
class-name: Mip70ItFinalizeR11
version: "1.0"
desc: Java test step class
steptype: NORMAL
lang: java
author:
  - Qore Technologies, s.r.o.
code: Mip70ItFinalizeR11-v1.0.qstep.java
base-class-name: QorusNormalStep
config-items:
  - name: header-table-name
    description: The R11 header table name
    type: string
    default_value: h3g_it_gl_int_header
  - name: msepl-it
    description: the mSEPL IT remote connection name
    type: string
    default_value: msepl-it
  - name: ebs11i
    description: the EBS 11i connection name
    type: string
    default_value: ebs11i
```

this can be found in the `demos` repo
