### ISSUE TITLE
backend is creating invalid YAML when saving allowed_values

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#233]
ex: create a config item with 2 `allowed_values` - the YAML output is as follows:
```
  - name: create-workflow-order-status
    default_value: READY
    allowed_values: READY,BLOCKED
    description: the initial status of the workflow order
    strictly_local: true
    config_group: Create Workflow Order
```

this results in the following when loading (`allowed_values` is a string with a comma, not a list):
```
david@greybeard:~/src/Qorus/git/building-blocks$ oload generic/BBM_CreateOrder-v1.0.qclass* -lvR
System exception: <builtin>:-1 (Qore): YAML-PARSER-ERROR: getEvent: unexpected event 'empty' when parsing YAML document
  parse_yaml() called at /Users/david/src/Qorus/test/qlib/Qyaml:117 (Qore builtin code)
  parse_yaml_file() called at /Users/david/src/Qorus/test/bin/oload:1578 (Qore user code)
  oload::parseAndValidateYaml() called at /Users/david/src/Qorus/test/bin/oload:686 (Qore user code)
  oload::constructor() called at <builtin>:-1 (Qore user code)
```

it works when fixed by hand:
```
  - name: create-workflow-order-status
    default_value: READY
    allowed_values:
      - READY
      - BLOCKED
    description: the initial status of the workflow order
    strictly_local: true
    config_group: Create Workflow Order
```
