### ISSUE TITLE
backend creates invalid YAML with multi-line text

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#234]
ex: 
```
  - name: create-workflow-duplicate-handling
    description: how should workflows with duplicate unique keys be handled:
- `SUCCESS`: the workflow order instance ID is returned normally
- `DUPLICATE`: the `DUPLICATE-ORDER-KEY` exception is rethrown
    default_value: SUCCESS
    strictly_local: true
    allowed_values:
      - SUCCESS
      - DUPLICATE
    config_group: Create Workflow Order Recovery
```

results in:
```
david@greybeard:~/src/Qorus/git/building-blocks$ oload generic/BBM_CreateOrder-v1.0.qclass* -lvR
System exception: <builtin>:-1 (Qore): YAML-PARSER-ERROR: getEvent: unexpected event 'empty' when parsing YAML document
  parse_yaml() called at /Users/david/src/Qorus/test/qlib/Qyaml:117 (Qore builtin code)
  parse_yaml_file() called at /Users/david/src/Qorus/test/bin/oload:1578 (Qore user code)
  oload::parseAndValidateYaml() called at /Users/david/src/Qorus/test/bin/oload:686 (Qore user code)
  oload::constructor() called at <builtin>:-1 (Qore user code)
```

it works after fixing by hand (added quotes and `\n` chars to the string):
```
  - name: create-workflow-duplicate-handling
    description: "how should workflows with duplicate unique keys be handled:\n
- `SUCCESS`: the workflow order instance ID is returned normally\n
- `DUPLICATE`: the `DUPLICATE-ORDER-KEY` exception is rethrown"
    default_value: SUCCESS
    strictly_local: true
    allowed_values:
      - SUCCESS
      - DUPLICATE
    config_group: Create Workflow Order Recovery
```
