### ISSUE TITLE
[FEATURE] Add triggers to class connections

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#264]
As discussed in order to connect created interface methods like service start method, job run method and step methods such as primary, validation, array etc. with class connections (so everything will work without need for writting any code), we can introduce a trigger attribute to the `class-connections` the following way:
```
class-connections:
  connection-1:
    - class: CC_JavaInit
      connector: CC_JavaInit_connector
      trigger: primary # tells to trigger this connector from step's primary method

    - class: BBM_JavaMiddle
      connector: BBM_JavaMiddle_connector
      mapper: crm-to-erp-order

    - class: BBM_CreateOrder
      connector: BBM_CreateOrder_connector
```

Here is a of possible triggers depending on interface type and base class in case of steps:
1) For services: **start, stop, init** and also in the future maybe user-defined methods.
2) For jobs: **run**
3) For steps it depends on the base class or more precisely on step type:
   1. **QorusNormalStep**: _primary, validation_
   2. **QorusNormalArrayStep**: _primary, validation, array_
   3. **QorusSubworkflowStep, QorusEventStep**: _primary_
   4. **QorusSubworkflowArrayStep, QorusEventArrayStep**: _primary, array_
   5. **QorusAsyncStep**: _primary, validation, end_
   6. **QorusAsyncArrayStep**: _primary, validation, end, array_

The list should be sent from the backend because only the backend knows what the actual type of the step is. And the list can be hardcoded. For services and job there is no data that should be accepted or returned by a trigger, so it's easy to implement, but for steps it's more complicated and depends on the step type. Let's do the easy stuff first and then disscuss more complicated cases afterwards.

**Comment by turlyalz** [comment]
changes to be applied on the frontend:

1) User should be able to add a mapper also between a trigger and the first connector in a connection. And mappers should be saved for connector in pre-order way:
```
class-connections:
  connection1:
    - class: BBM_SalesforceStreamBase
       connector: BBM_SalesforceStreamBase_connector_1
       event-based: true # default is false
       # mapper: crm-to-erp-order

2) For services we should provide to user a possibility to use user defined methods as triggers. The easiest way to do so without changing current pages order (first user fills service metadata and then he can add class-connections and after that on the second page he can add service methods) is in the trigger dropdown user will be able to add arbitrary trigger that will be automatically added to his methods with the same name as the trigger name and with description something like: user method used as trigger for connectionX. And the method cannot be deleted until user will delete the appropriate trigger.
3) Add `type` tag to `class-connectors` tag for classes - enum type - event or default.
4) Based on the type of class-connector user will have a possibility to mark a connector used in a connection as `event-based` (the tag should be added) - true or false (default is false). Event-based connectors cannot have mappers.

**Comment by turlyalz** [comment]
Regarding 2. point decided to add the `manage class-connection` button to both pages

**Comment by turlyalz** [comment]
Updates to apply:

Connectors will have required field type:
```
class-connectors:
  - name: BBM_SalesforceStreamBase_connector_1
    type: event # or input, output, input-output
    method: messageCallbackImpl
    provider:
      name: qoretechnologies
      path: /building-blocks/salesforce/stream-event
      type: type
```

**Comment by turlyalz** [comment]
Known issues:
1) When creating a class and adding a class connector the name for the first connector is not prefilled automatically as it's done for the next ones (minor)
2) When adding a connector to class-connections: selecting some connector from a class and then changing the class to other way the previously selected connector from different class remains selected (major)
3) Increase pop-up (or make it resizable) height for class-connections - two connectors with a trigger don't fit the height (minor)
4) To delete a mapper from a class connection I need to open it first (minor)
5) Allow users to create a class connection with one connector which is not event-based and has trigger (major)
6) The first connector in a connection can be event-based or can have a trigger, but not both at the same time (major)
7) Internal data is stored to YAML: (major)
```
class-connections:
    Connection_1:
      - class: CC_TestClass1
        connector: OutputConnector
        event-based: true
        inputProvider: null
        isConnectorEventType: false
        isEditing: true
        mapper: null
        outputProvider: null
        trigger: run
```
