### ISSUE TITLE
[BUG] invalid path saved for request-response providers in mappers

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#293]
incorrect example (created by the IDE with the latest build):
```
    mapper-output:
        custom-fields: {}
        name: rest-billing-demo
        path: /accounts/POST/request
        subtype: request
        type: connection
```

the subtype `request` is correct, but this should not be in the path - it causes the server to fail - it should look like:
```
    mapper-output:
        custom-fields: {}
        name: rest-billing-demo
        path: /accounts/POST
        subtype: request
        type: connection
```
