### ISSUE TITLE
allow the null provider to be chosen as input only in mappers

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#294]
the YAML generated should look like:
```
    mapper-input:
        custom-fields: {}
        name: "null"
        path: /
        type: factory
```
