### ISSUE TITLE
[BUG] if the path string is missing the training / the webview crashes

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#304]
ex:
```
    mapper-output:
        custom-fields: {}
        name: rest-billing-demo
        path: /accounts/POST
        subtype: request
        type: connection
```
causes a crash

```
    mapper-output:
        custom-fields: {}
        name: rest-billing-demo
        path: /accounts/POST/
        subtype: request
        type: connection
```
works perfectly
