### ISSUE TITLE
[BUG] backend generates invalid YAML

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#336]
strings are being saved with incorrect quotes - ex:
```
  - name: rest-recovery-response-location
    default_value:
        null
    type: "*string"
    description: "the location of the recovery value in the recovery response message to check; the value to check must be set with "rest-recovery-response-value"; conflicts with "rest-recovery-id-location"; only used if "rest-id-location" is not set; the value here is related to the entire HTTP response; prefix with "body." to compare values in the response message body (ex: "body.account.ID")\n"
    strictly_local: true
    config_group: Rest Action Recovery
```

Strangely enough the invalid strings were saved when adding connectors to an object, while editing config item descriptions did not result in any invalid YAML being saved.
