### ISSUE TITLE
[BUG] Information about service methods is not displayed on mouse hover

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#396]
Information about the service is shown, but for the method it shows: (No description found)

the service code:
```
%new-style
%strict-args
%require-types
%enable-all-warnings

class BasicsSimpleService inherits QorusService {
    init() {
        logInfo("service is initialized");
    }
}
```

the yaml:
```
# This is a generated file, don't edit!
type: service
name: basics-simple-service
desc: "Service simple example"
author:
  - Qore Technologies, s.r.o.
base-class-name: QorusService
class-name: BasicsSimpleService
groups:
  - BASIC-TRAINING-EXCHANGE-APP
lang: qore
autostart: true
version: "1.0"
servicetype: USER
code: basics-simple-service-1.0.qsd
methods:
  - name: init
    desc: initialization of the service
```
