### ISSUE TITLE
[BUG] mapper code is not deployed correctly; only the yaml file is sent to the server

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#407]
ex:
```
Files to deploy:
    arpm/prepare-zeyos-action-step-order-data-code-1.0.qmc.yaml
Deployment to meteor - https://localhost:8011 has started ...
options: {"allow-redef":false,"force":false,"validate":true,"reload":true,"verbosity-level":1}
  ... response: {"id":15,"href":"api/latest/development/deploy/15"}
uri https://localhost:8011/api/latest/development/deploy/15
1s   checking deployment progress (ID: 15) ... 
... System exception: /Users/david/src/Qorus/test/bin/oload:1539 (Qore): READONLYFILE-OPEN-ERROR: cannot open '/Users/david/src/Qorus/test/user/arpm/prepare-zeyos-action-step-order-data-code-1.0.qmc': No such file or directory (arg: 2)
ReadOnlyFile::constructor() called at /Users/david/src/Qorus/test/bin/oload:1539 (Qore builtin code)
oload::readCode() called at /Users/david/src/Qorus/test/bin/oload:1623 (Qore user code)
oload::parseAndValidateYaml() called at /Users/david/src/Qorus/test/bin/oload:693 (Qore user code)
oload::constructor() called at <builtin>:-1 (Qore user code)
, status: FAILED
Deployment failed (ID: 15)
```

The `prepare-zeyos-action-step-order-data-code-1.0.qmc` file referenced in the yaml is not sent:
```
# This is a generated file, don't edit!
type: mapper-code
name: prepare-zeyos-action-step-order-data-code
desc: "code for the ARPM service"
author:
  - Qore Technologies, s.r.o.
class-name: PrepareZeyosActionStepOrderDataCode
version: "1.0"
code: prepare-zeyos-action-step-order-data-code-1.0.qmc
methods:
  - name: getStaticData
    desc: returns the static data hash
```

```
david@meteor:~/src/Qorus/git/demos/arpm$ ls -l prep*qmc*
-rw-r--r-- 1 david staff 681 Feb 29 16:09 prepare-zeyos-action-step-order-data-code-1.0.qmc
-rw-r--r-- 1 david staff 369 Feb 29 15:56 prepare-zeyos-action-step-order-data-code-1.0.qmc.yaml
```
