### ISSUE TITLE
[FEATURE] add support for dynamic types

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#433]
includes creating and editing types + deleting types

types are means to have paths and the type definition itself - example types:
```
david@meteor:~/src/Qorus/git/qorus/test/types$ qrest system/metadata/types
list: (18 elements)
  [0]="/qore/hash"
  [1]="/qore/ftp/event"
  [2]="/qore/sftp/event"
  [3]="/qore/fsevents/event"
  [4]="/qoretechnologies/qorus-api/workflows/create-order/request"
  [5]="/qoretechnologies/qorus-api/workflows/create-order/response"
  [6]="/qoretechnologies/building-blocks/sftp/event"
  [7]="/qoretechnologies/building-blocks/salesforce/stream-event"
  [8]="/qoretechnologies/building-blocks/create-order/request"
  [9]="/qoretechnologies/building-blocks/create-order/response"
  [10]="/qoretechnologies/building-blocks/rest-action/request"
  [11]="/qoretechnologies/building-blocks/rest-action/response"
  [12]="/qoretechnologies/building-blocks/data-provider-search/input"
  [13]="/qoretechnologies/building-blocks/generic/string"
  [14]="/qoretechnologies/building-blocks/generic/record-list"
  [15]="/qoretechnologies/building-blocks/ftp/event"
  [16]="/qoretechnologies/qorus/regression/issue-3445-hash"
  [17]="/qoretechnologies/qorus/regression/issue-3445-string"
```

So there are only these two pieces of information to be acquired / edited with types.

In the DB, types are stored as serialized `AbstractDataProviderType` objects (so in an opaque binary format).

type schema:
```
required:
  type:
    type: string
    allowed-values:
    - type
  path:
    type: string
    max-length: 4000
  typeinfo:
    type: hash
```

example yaml file used for testing (`issue-3445-string.qtype.yaml`):
```
# This is a generated file, don't edit!
type: type
path: qoretechnologies/qorus/regression/issue-3445-string
typeinfo:
  base_type: string
  can_manage_fields: false
  mandatory: true
  name: string
  options:
      qore.no_null: true
  supported_options:
      qore.no_null:
          desc: >-
              if True then NULL is not supported on input if
              NOTHING is also not accepted
          type: bool
  typename: string
  types_accepted:
      - string
  types_returned:
      - string
```

For the beginning, it's fine to only support hash types similar to mapper input/output records, if it makes the implementation easier.  This is the only type that's relevant at the moment anyway, because currently there is no useful way to customize base types like the `string` example above.

**Comment by davidnich** [comment]
example with a hash type (the only type that we need to support in the beginning):
```
# This is a generated file, don't edit!
type: type
path: qoretechnologies/qorus/regression/issue-3445-hash
typeinfo:
  base_type: hash<auto>
  can_manage_fields: false
  fields:
    key:
      canBeNull: false
      desc: key
      isCustom: true
      name: key
      type:
        base_type: string
        can_manage_fields: false
        fields: {}
        mandatory: true
        name: string
        options:
          qore.no_null: true
        supported_options:
          qore.no_null:
            desc: >-
                if True then NULL is not supported on
                input if NOTHING is also not accepted
            type: bool
          string.encoding:
            desc: >-
                the output encoding when writing to the
                type
            type: string
          string.max_size_chars:
            desc: >-
                the maximum length of the string in
                characters
            type: integer
        typename: string
        types_accepted:
          - string
        types_returned:
          - string
    subrec:
        canBeNull: false
        desc: subrec
        isCustom: true
        name: subrec
        type:
            base_type: auto
            can_manage_fields: true
            fields:
                value:
                    canBeNull: false
                    desc: value
                    isCustom: true
                    name: value
                    type:
                        base_type: string
                        can_manage_fields: false
                        fields: {}
                        mandatory: true
                        name: string
                        options:
                            qore.no_null: true
                        supported_options:
                            qore.no_null:
                                desc: >-
                                    if True then NULL is not supported on
                                    input if NOTHING is also not accepted
                                type: bool
                            string.encoding:
                                desc: >-
                                    the output encoding when writing to the
                                    type
                                type: string
                            string.max_size_chars:
                                desc: >-
                                    the maximum length of the string in
                                    characters
                                type: integer
                        typename: string
                        types_accepted:
                            - string
                        types_returned:
                            - string
            mandatory: false
            name: auto
            options: null
            supported_options: null
            typename: any
            types_accepted:
                - any
            types_returned:
                - any
  mandatory: true
  name: hash<auto>
  options:
      qore.no_null: true
  supported_options:
      qore.no_null:
          desc: >-
              if True then NULL is not supported on input if
              NOTHING is also not accepted
          type: bool
  typename: hash
  types_accepted:
      - hash<auto>
  types_returned:
      - hash<auto>
```
