### ISSUE TITLE
[FEATURE] add support for wf static data type definitions

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#437]
the wf YAML schema has been updated with the following optional key:
```
  staticdata-type:
    type: hash
```

The assumption is that the `staticdata-type` key will contain a hash with the same information as mapper input and output types to describe the type.

Here is an example of wf YAML with a static data definition:
```
# This is a generated file, don't edit!
type: workflow
name: STATIC-DATA-TEST
desc: "Workflow static data test"
author:
  - Qore Technologies, s.r.o.
remote: false
sla_threshold: 10
steps:
    [
        "WfStaticDataTestStep:1.0"
    ]
version: "1.0"
autostart: 0
staticdata-type:
    type: type
    name: qoretechnologies
    path: qorus/regression/issue-3446-hash
```
