### ISSUE TITLE
[BUG] error in config item value hash handling

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#467]
I have a config item of type `auto` and I'm trying to give it a hash value.

The value I am giving is:
`{body: {filters: {type: 6, creationdate: {'>': "$parse-value:{%EVAL=get_epoch_seconds($pstate:last_executed??{2000-01-01})}"}}}}`

The IDE accepts this as valid YAML, but serializes it as a string in the yaml file, despite having chosen type `hash` in the IDE:
```
  - name: dataprovider-request-input
    value:
        "{body: {filters: {type: 6, creationdate: {\">\": \"$parse-value:{%EVAL=get_epoch_seconds($pstate:last_executed??{1970-01-01})}\"}}}}"
    parent:
        interface-type: class
        interface-name: BBM_DataProviderRequest
        interface-version: "1.0"
    is_value_templated_string: false
```

<img width="1743" alt="Screen Shot 2020-03-24 at 8 15 37 AM" src="https://user-images.githubusercontent.com/13432105/77398374-ac8b5580-6da7-11ea-9ba0-270ecab4bbcf.png">
