### ISSUE TITLE
[BUG] mapper code shows an incorrect error

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#526]
error shown in the mapper code (code) file: `Mismatch in source and yaml file: method getName in  is not present in the yaml file`

how to reproduce: go to the `demos` repo in the `develop` branch and open `telco-om/telco-create-billing-account-1.0.qmc`

the `getName()` method exists in the Qore code and also in the YAML - for some reason, the IDE believes there is a mismatch though:
<img width="1917" alt="Screen Shot 2020-05-01 at 9 26 45 AM" src="https://user-images.githubusercontent.com/13432105/80789979-e8c38a00-8b8d-11ea-8f28-60d785d31dc7.png">

YAML:
```
# This is a generated file, don't edit!
type: mapper-code
name: TelcoCreateBillingAccount
version: "1.0"
class-name: TelcoCreateBillingAccount
code: telco-create-billing-account-1.0.qmc
methods:
  - name: getName
    desc: retrieve the name
```
