### ISSUE TITLE
[BUG] submapper_options are not saved correctly

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#529]
the front end correctly handles the value as a hash and will only accept valid YAML for a hash, however the backend saves the YAML string quoted - the `submapper_options` key requires a hash and is defined as follows:
```
    submapper_options : hash: (5 members)
      desc : "allows a parent mapper to affect the options of the submapper based on current data; use \"$rec:<field>\" to refer to mapped data in the current parent mapper row to affect submapper options"
      value_type : "hash"
      requires_field_type : False
      unique_roles : list: (1 element)
        [0]="submapper_options"
      requires_roles : list: (1 element)
        [0]="submapper"
```

the YAML saved is a string:
```
    children:
        name: child_recs
        submapper: mapper-test-child
        submapper_options: '{parent: "$rec:id"}'
```

editing the YAML allows the object to be oloaded, but then the value is displayed as `[object Object]`:
<img width="2055" alt="Screen Shot 2020-05-04 at 8 18 37 AM" src="https://user-images.githubusercontent.com/13432105/80940404-fb350200-8ddf-11ea-85cd-b623b5d48211.png">
