### ISSUE TITLE
[FEATURE] FSM

### ISSUE THREAD

**Issue by turlyalz** [qoretechnologies/qorus-vscode#547]
Add support for FSM for steps, services and jobs. The FSM definition is here: https://git.qoretechnologies.com/qorus/qorus-object-parser/blob/feature/3485-fsm-pipelines/Qyaml/validation/fsm_definition.yaml

Each of the above interfaces can have multiple FSM definitions, which are defined under the `fsm` tag in the inteface definition. 

Examples of interface with FSM can be found here: https://git.qoretechnologies.com/qorus/qorus/tree/feature/3485-fsm-pipelines/test/issue-3485

FSM's main tag is `states` , it is a hash, where the key is the name of the state. 
States have the following tags:
-  `action` - one of the following: connector, pipeline (#546) or mapper.
- `transitions` - defines relations to other states. Transition can be a relation to another state or to another FSM (it more means that the current FSM triggers another one). Transitions happen under some condition, which is defined by the `condition` tag.
The possible conditions:
 - default - no condtion
 - connector - condition connector type (add condition type to connector types)
 - expression - any string that can be evaluated (TBD - how to implement)
Each state can also have input/output types and two flags to mark if it's an initial/final state.

**Comment by davidnich** [comment]
current issues:
* cannot deploy FSM: there are 3 errors in the YAML
 1) the `id` field is not allowed
 2) the `x` and `y` values must be floats - so integer numbers must be written with `.0` on the end - i.e. `148` will fail, while `148.0` will work
 3) the state names in transitions must be quoted if the name is an integer ex: `state: 2` fails, while `state: '2'` works

**Comment by davidnich** [comment]
not possible to scroll the target directory list in an FSM modal:
<img width="2135" alt="Screen Shot 2020-07-04 at 3 35 11 PM" src="https://user-images.githubusercontent.com/13432105/86513636-1e922280-be0c-11ea-8501-8773640eaa16.png">

**Comment by davidnich** [comment]
@martin-zemek config item issues
- [ ] changing a config item on an FSM and then hitting the `Reset` button in the state dialog does not reset the config item value
- [ ] (probably the same cause as above) after changing a config item value and then reloading the same FSM with the button on the hierarchy view, there is no warning that changes will be lost and also after reloading the same FSM the changed config item value is still changed - although in the file it still has the original value - to get the original value back in the IDE, I had to reload the window
- [ ] after changing a value of a config item a second time and hitting `Submit` for the FSM, I get the error: `FSM with name xxxx already exists` - hitting `Submit` again repeats the error
- [ ] list value of config item type `any` is not displayed correctly - displayed as `[]` although the actual value is:
```
          - name: log-message-args
            value:
                [-1,55]
            parent:
                interface-name: BBM_LogMessage
                interface-type: class
                interface-version: "1.0"
```
see:
<img width="1856" alt="Screen Shot 2020-08-03 at 8 15 25 AM" src="https://user-images.githubusercontent.com/13432105/89151546-82218400-d561-11ea-8c2e-fb8aefde2eb2.png">
<img width="1856" alt="Screen Shot 2020-08-03 at 8 16 47 AM" src="https://user-images.githubusercontent.com/13432105/89151648-b8f79a00-d561-11ea-8413-58f34dfba8e0.png">

The above tests were done with the `chatbot/authorize-payment.qfsm.yaml` FSM in the demos repo in the `develop` branch

**Comment by martin-zemek** [comment]
As to "list value of config item type any is not displayed correctly":
The yaml file is incorrect, obviously it was created by hand which is wrong and always be.
For a config item of type any there must be value_true_type entry, in this case:
```
  -     name: log-message-args
        value:
                [-1,55]
        value_true_type: list
        parent:
                interface-name: BBM_LogMessage
                interface-type: class
                interface-version: "1.0"
```
