### ISSUE TITLE
[BUG] tags are not serialized as strings in all cases

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#690]
ex: the tag `true` is serialized as-is and is interpreted as a YAML `true` value instead of as the string `"true"`:
<img width="2085" alt="Screen Shot 2020-12-16 at 12 06 49 PM" src="https://user-images.githubusercontent.com/13432105/102340882-5692b980-3f97-11eb-9cb3-41166eca7899.png">

YAML:
```
tags:
    UI-NAME: Router performance check
    UI-DURATION: 3 - 5 minutes
    UI-ENABLED: true
```

error:
```
ERROR: /Volumes/Nichols External 1TB/david/src/Qorus/git/maxis-tssp/qorus/MAXIS-WIFI-ISSUE-1.0.qwf.yaml: QYAML-VALIDATION-ERROR: /Volumes/Nichols External 1TB/david/src/Qorus/git/maxis-tssp/qorus/MAXIS-WIFI-ISSUE-1.0.qwf.yaml: element: True
of field: "tags" of type: "hash" has unexpected type: bool, expected type: string
```
