### ISSUE TITLE
error saving class with processor; invalid "options" field saved in processor

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#692]
After I added a tag to the file `test/issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml`, I got the following diff:
```
diff --git a/test/issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml b/test/issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml
index faad3c70c..5a5a35e01 100644
--- a/test/issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml
+++ b/test/issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml
@@ -2,13 +2,16 @@
 type: class
 name: Issue3485PythonProcessor1
 desc: Python processor test
+lang: python
 author:
   - Qore Technologies, s.r.o.
 base-class-name: AbstractDataProcessor
-lang: python
 processor:
-    {}
-version: "1.0"
+    options: null
+version: '1.0'
+
+tags:
+    TEST: issue-3485-class
```

The problem is that the processor options are changed from:
```
processor:
    {}
```

which is valid to:
```
processor:
    options: null
```

which is not.   Error in oload:
```
david@meteor:~/src/Qorus/git/qorus/test$ oload -lvR ./issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml 
ERROR: /Volumes/Nichols External 1TB/david/src/Qorus/git/qorus/test/issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml: QYAML-VALIDATION-ERROR: /Volumes/Nichols External 1TB/david/src/Qorus/git/qorus/test/issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml: field: processor has unexpected type: hash, expected one of the types: list: ("processor")
possible errors:
    1) QYAML-VALIDATION-ERROR: /Volumes/Nichols External 1TB/david/src/Qorus/git/qorus/test/issue-3485/Issue3485PythonProcessor1-1.0.qclass.yaml: unexpected field found: options; valid fields: ["processor-input-type", "processor-output-type"]; YAML: hash: (1 member)
         options : <NOTHING>
```

the `options` field under `processor` is invalid - also a processor with input types is saved with this invalid key:
```
processor:
    processor-input-type:
        type: type
        name: qore
        can_manage_fields: true
        path: /hash
    processor-output-type:
        type: type
        name: qore
        can_manage_fields: true
        path: /hash
    options: null
```

Leading to the same error - oload rejects it, because the `options` key is not in the schema
