### ISSUE TITLE
[FEATURE] implement support for pod resource limits for stateless services for Qorus 5.1

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#734]
ex (from the k8s statefulset yaml):
```
            limits:
              cpu: "8000m"
              memory: 16Gi
            requests:
              cpu: "100m"
              memory: 200Mi
```

currently these parameters are copied from the qorus master pod, which is where all the interfaces run, so it needs to be large, and it does not make sense for a small service to have such large limits

We need to set relatively small defaults that can be changed in the IDE or at runtime using the UI
