### ISSUE TITLE
add support to genere service methods

### ISSUE THREAD

**Issue by sejvlond** [qoretechnologies/qorus-vscode#76]
when we are able to generate a service from our IDE (meta tags and skeleton of code with just an init method)
it would be nice to be able to generate more service methods, documentation for service methods:
https://qoretechnologies.com/manual/qorus/latest/qorus/implementingservices.html

they have metadata similiar to a service itself
```
lock     N     must be either none, read, or write (default none), to determine how the service's RWLock will be grabbed before the method is executed
name     N     The name tag must be defined for class-based service methods; also a public method with this name must be defined in the code block as well
desc     Y     Description of the method object
author     N     The optional author of the method, in case it differs from the service's author
internal     N     If this boolean flag is set to True, then the method will not be automatically exported through the any network interface
write     N     If this boolean flag is set to True, then the method will be marked as a write method, meaning that external callers will have to have the CALL-USER-SERVICES-RW role to call the method if RBAC security is enabled
```

where only name and desc are required (not even name actually) and the user can add as many as he wants, 0-inf (I think 0 is fine, not sure tho), and we can generate a basic skeleton for each method like

```
# .... (meta tags for service)

class MyService inheritx XXX {    # (already generated)

    # name: init
    # desc: initializes the service
    init() {
    }

    # name: other
    # desc: an example static service method
    static other() {
    }

}
```

but check with @turlyalz how's the new syntax for methods - the meta tags won't be above a code now, but in the separate yaml instead, I think name will be mandatory, etc

In the future, editing such method would be nice, adding new etc

**Comment by turlyalz** [comment]
Please check https://git.qoretechnologies.com/qorus/qorus-object-parser/tree/feature/3102_yaml_format/Qyaml/validation. There are YAML schema validation files for qorus objects. YAML syntax examples can be found here: https://git.qoretechnologies.com/qorus/qorus-object-parser/tree/feature/3102_yaml_format/Qyaml/test. Service methods with the new syntax should be defined in service metadata YAML file. 

```
methods:
  - name: init
    desc: init method
  - name: getString
    desc: returns a string
  - name: echo
    desc: returns the argument
  - name: echoInternal
    desc: returns the argument; internal only
    internal: true
  - name: getInt
    desc: get an int
  - name: throwException
    desc: throws an exception
    lock: read
    write: false
    author: Qore Technologies
```
