### ISSUE TITLE
[BUG] webview crashes after removing a templated value from a config item and then reopening the interface

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#850]
YAML looks like:
```
config-items:
  - name: test
    is_value_templated_string: true
    description: test
    config_group: test
    strictly_local: true
    type: int
```

`is_value_templated_string` is left in the YAML even when the value is removed

after removing this from the YAML, the interface can be opened again
