### ISSUE TITLE
[BUG] removing a value from a config item of type "any" results in in valid YAML

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#851]
invalid config item YAML:
```
config-items:
  - name: test
    value:
        null
    description: test
    config_group: test
    strictly_local: true
    type: any
    value_true_type: null
```

`value_true_type: null` should be `value_true_type: "null"`
