### ISSUE TITLE
[BUG] config items of type any are not handled correctly with values of type hash

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#859]
steps to recreate:
1. create a job with a config item of type `any`
2. add a hash value to the config item - ex: `a: 1`
3. save the job

go back and look at the config item value - it has turned into ... something else - the IDE shows it as a date (if you only wrote one key) or a string (if you write a hash with 2 or more keys) - with YAML that looks like this:
```
config-items:
  - name: test
    value:
        "a: 1"
    description: test
    config_group: test
    strictly_local: true
    type: any
    value_true_type: "hash"
```

if you manually update the config item value to:
```
config-items:
  - name: test
    value:
        a: 1
    description: test
    config_group: test
    strictly_local: true
    type: any
    value_true_type: "hash"
```

Then it works properly.
