### ISSUE TITLE
[BUG] nullable inherited config items cannot be saved with a null value

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#865]
after setting an inherited config item of type `*hash` to null in the UI, the YAML is saved like this:
```
- name: dataprovider-search-options
    parent:
        interface-type: class
        interface-name: BBM_DataProviderSearch
        interface-version: '1.0'
    value_true_type: "null"
```

This is then loaded and shown as unset in the UI.

If I change it to:
```
- name: dataprovider-search-options
    parent:
        interface-type: class
        interface-name: BBM_DataProviderSearch
        interface-version: '1.0'
    value_true_type: "null"
    value: null
```

Then it is loaded correctly.  If I save it again though, it gets transformed to the following invalid YAML:
```
- name: dataprovider-search-options
    parent:
        interface-type: class
        interface-name: BBM_DataProviderSearch
        interface-version: '1.0'
    value_true_type: null
```
