### ISSUE TITLE
[BUG] cannot save a config item value in an FSM connector with type any

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#896]
the `value_true_type` value is not set:
```
QYAML-VALIDATION-ERROR: /home/david/src/Qorus/git/training/03_basics_building_blocks/01_exchange_rates_app/09_exchange_currency_workflow/basics-exchange-rates-insert-to-orders-table.qfsm.yaml: field: value_true_type has unexpected type: nothing, expected type: string
```

from the yaml:
```
                  - name: dataprovider-create-input
                    value:
                        "{$qore-expr:{$qore-expr-value:{$local:value} + {\"id\": $local:{key}.toInt()}}"
                    parent:
                        interface-type: class
                        interface-name: BBM_DataProviderRecordCreate
                        interface-version: '1.0'
                    value_true_type: null
```

Using the `BBM_DataProviderRecordCreate` building block in an FSM.
