### ISSUE TITLE
[BUG] config items values with type "any" can be saved / loaded incorrectly

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#899]
ex: save a value with type string as `a: 1`

after saving the config item (the interface does not need to be saved), the value will be reflected in the IDE as a hash

if saved, the yaml reflects type `hash` instead of `string`:
```
  - name: dataprovider-create-input
    value:
        a: 1
    parent:
        interface-type: class
        interface-name: BBM_DataProviderRecordCreate
        interface-version: '1.0'
    value_true_type: hash
```
