### ISSUE TITLE
[FEATURE] implement an "Api call" FSM state in the IDE

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#947]
A new FSM state type should be implemented in the IDE as described below. 

Details:
- fsm state action type: `apicall`
- value format: data provider hash as in mappers - i.e. any data provider where `supports_request` = `true` - note there is no `request` or `response` on the end of `api.path` below, which is different from mappers which require a defined type

YAML FSM example:
```
# This is a generated file, don't edit!
type: fsm
name: test-fsm
desc: test fsm
states:
    '1':
        name: initState
        initial: true
        execution_order: 1
        action:
            type: apicall
            value:
              type: factory
              name: qorus-api
              can_manage_fields: false
              path: /workflows/create-order
              custom-fields: {}
        id: state1
        position:
            x: 175.125
            'y': 30.17578125
        type: state
```
