### ISSUE TITLE
[FEATURE] add support for API management

### ISSUE THREAD

**Issue by davidnich** [qoretechnologies/qorus-vscode#968]
## Service Changes

A new attribute should be added to services - `api-manager` - this option will hold the following options:
- `factory`: the name of a data provider factory supporting API management; retrieved with the REST call: `GET /api/latest/dataprovider/factories?context=ui&context=api` (currently there are only two: `soap` and `swagger`).
- `provider-options`: options needed to create the data provider factory - the IDE can query the factory options from Qorus using `context=ui` (ex: `GET /api/latest/dataprovider/factories/swagger?context=ui&context=api`)
  - the user then would fill in the options required by the factory constructor, one of which will be a file option with type `file-as-string`; the file's contents will be sent to the server as a string; the API will validate the factory options and return a list of API endpoints; the API is: `PUT /api/latest/dataprovider/factories/<factory>/provider/apiEndpoints?context=ui&context=api`; `provider_options` should be provided in the message body
- `endpoints`: a list of endpoint hashes - one endpoint for each endpoint retrieved with the above call.  Each hash will have the following keys:
  - `endpoint`: the endpoint name retrieved in the call above
  - `method` | `fsm`: the service method name or FSM used to serve the API call

Ex:
```
# This is a generated file, don't edit!
type: service
name: issue-3834-swagger
desc: 'issue #3834 Swagger test'
lang: qore
author:
  - Qore Technologies, s.r.o.
autostart: true
base-class-name: QorusService
class-name: Issue3834Swagger
groups:
  - regression
  - test
remote: false
version: '1.0'
resource:
  - billing-demo-1.0.yaml
servicetype: USER
code: issue-3834-swagger-1.0.qsd
methods:
  - name: init
    desc: init method
  - name: account_put
    desc: method
  - name: account_delete
    desc: method
  - name: accounts_get
    desc: method
  - name: accounts_post
    desc: method
api-manager:
  factory: swagger
  provider-options:
    schema: resource://billing-demo-1.0.yaml
    root-uri: issue-3834
    auth-name: permissive
  endpoints:
    - endpoint: /accounts/*/GET
      type: fsm
      value: issue-3834-get-account
    - endpoint: /accounts/*/PUT
      type: method
      value: account_put
    - endpoint: /accounts/*/DELETE
      type: method
      value: account_delete
    - endpoint: /accounts/GET
      type: method
      value: accounts_get
    - endpoint: /accounts/POST
      type: method
      value: accounts_post
```
